default_install_hook_types: [pre-commit, commit-msg]
default_stages: [commit, manual]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files
            args:
                - '--maxkb=10000'
          - id: end-of-file-fixer
            exclude: '\.ipynb$'
          - id: check-json
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: check-case-conflict
          - id: detect-aws-credentials
            args:
                - '--allow-missing-credentials'
          - id: check-symlinks
          - id: check-merge-conflict
            stages:
                - commit
                - merge-commit
                - manual
          - id: requirements-txt-fixer
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.16.0
      hooks:
          - id: commitlint
            additional_dependencies: ['@commitlint/config-conventional@19.2.2']
            pass_filenames: true
            stages:
                - commit-msg
    {%- if cookiecutter.linter_name == "pylint" %}
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            name: isort (python)
            stages:
                - commit
                - manual
    {%- elif cookiecutter.linter_name == "ruff" %}
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.6.7
      hooks: 
      - id: ruff
    {%- endif %}
    - repo: local
      hooks:
          - id: black
            name: black
            entry: black
            args: [--config=./pyproject.toml]
            language: system
            types: [python]
          {%- if cookiecutter.linter_name == "pylint" %}
          - id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
          {%- endif %}
          {%- if cookiecutter.install_jupyter == "yes" %}
            {%- if cookiecutter.linter_name == "pylint" %}
          - id: nbqa-pylint
            name: nbqa-pylint
            entry: nbqa pylint
            language: system
            files: \.ipynb
            args:
                - --disable=pointless-statement,duplicate-code,expression-not-assigned
                - --const-rgx=(([A-Z_][A-Z0-9_]*)|(__.*__)|([a-z_][a-z0-9_]{0,50}))$
            {%- elif cookiecutter.linter_name == "ruff" %}
          - id: nbqa-ruff
            name: nbqa-ruff
            entry: nbqa ruff
            language: system
            files: \.ipynb
            {%- endif %}
          {%- endif %}
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
            stages:
                - commit
                - manual
            exclude: data/
