name: '{{cookiecutter.env_name}}'
channels:
    - conda-forge
dependencies:
    - black=24.4.2
    {%- if cookiecutter.install_jupyter == 'yes' %}
    - jupyter=1.0.0
    - nbqa=1.8.5
    {%- endif %}
    {%- if cookiecutter.linter_name == "pylint" %}
    - pylint=3.2.5
    {%- elif cookiecutter.linter_name == "ruff" %}
    - ruff=0.6.7
    {%- endif %}
    - python=3.10.9
    - pre-commit=3.7.1
